### ISSUE TITLE
Wrap Structs

### ISSUE THREAD

**Issue by RobLoach** [stfwi/duktape-cc#2]
Using duktape-cc is there an easy way to wrap struct objects? Or classes?

**Comment by stfwi** [comment]
Hi, apologies for the late response. I have currently no template based object wrapping, and would more encourage to use the Duktape API wrappers to meet the flexibility of JS objects (https://duktape.org/api.html).

**Comment by stfwi** [comment]
Before I add a label, is that actually a feature request or a question ? ;)

**Comment by RobLoach** [comment]
Hey, thanks for getting back... I suppose this is mostly a question as to how it's done. 

Maybe the "feature request" would be to add some documentation? If you point me to some examples or something, I could write it.

**Comment by stfwi** [comment]
Hi Rob, thanks for that. I have to admit I need to dig into the matter again - did some experiments with "sub-optimal-results" a time ago.
The thing is that JS very flexible, and objects have a different life cycle due to garbage collection. If I recall correctly there is e.g.
the duktape c++ glue project, which covers template based class conversion. The thing is that in the applications where I needed objects I
was in the end bound to use the Duktape API (via `api` class) to dynamically check function and constructor arguments - JS coders want
flexibility (e.g. to specify a config object for construction, or copy construction, or with optional arguments, etc). The `fs.find(...)`
function in this project is one example.

Also approaches to make a conversion between plain object and `std::map<string, T>` was not really satisfying, because objects in JS seldom
have the same type `T`, except `T` would be a kind of variant type in c++ - which makes it better and less complicated to directly access the
JS object.

So I deferred the implementation of objects and class wrapping until a getting bright idea ;). The tendency I have is not trying to force JS
in into the strict c++ world, but more getting a helpers to construct, identify/verify the c++ object pointer for a JS object, destruction/leak
safety, and making easier property access definitions. I'll check the changes in Duktape and probably it's also time to assume that at least
c++14 can be forced as std by now.

**Comment by RobLoach** [comment]
I can see where the complexity comes in. Is there a JSON API we could integrate with to handle the conversion? Would that even make sense?

You are right about std:map being the incorrect data model.

**Comment by stfwi** [comment]
I have a very old JSON parser implementation here (c++98!): http://atwillys.de/content/cc/cpp-json-parser-compser-class-template/. The funny thing is that also there the structure has to be analyzed to work with it. For quickly accessing canonical object paths there is the `select(path)` method in the  `duktape::engine`.

In a still abstract and scratchy way I am thinking about a object wrapping about like this:


```
class circle {...};

// wrapper object with class name in js
auto js_circle = duktape::native_object<circle>("Circle");

// template based function pattern
js_circle.constructor([](double x, double y, double r) {
  return circle(x,y,z); // underlaying unique pointer, JS-class-relation e.g. using typeid
});

// JS dynamic args
js_circle.constructor([](duktape::api stack){
  if(stack. ...) {
    return circle(...);
  } else if( ... ) {
    return circle(...);
  }
});

// property, wrapped with duk_def_prop() or stack.def_prop() respec
js_circle.property("x",
  // getter
  [](const circle& c){ return c.x(); },
  // setter, if void or omitted the prop is readonly/const
  [](circle& c, api stack){ return c.x(stack.get<double>(-1)); }
);

// method
js_circle.method("move", [](circle& c, api stack){
  if((stack.top()==2) && stack.is<double>(0) && stack.is<double>(1)) {
    // called e.g. mycircle.move(10,20);
    c.x( stack.get<double>(0) );
    c.y( stack.get<double>(1) );
  } else if((stack.top()==1) && stack.is_object(1)) {
    // called like mycircle.move({x:10, y:20});
    // only skel for example, no checks ...
    c.x( stack.get<double>(0, "x") ); // object is arg0
    c.y( stack.get<double>(0, "y") ); // object is arg0
  } else {
    throw duktape::script_error("invalid arguments for Circle.move blablub");
  }
}););

// register in JS engine
js.define(cv);
```

**Comment by stfwi** [comment]
Ok, so I added a first implementation for native object wrapping, similar to the code described above. Does this fit your needs (can we close this issue)?

**Comment by stfwi** [comment]
Is this issue still relevant for your application? (stalling issue)

**Comment by RobLoach** [comment]
This is incredible! Thanks so much :+1: 

Haven't had a chance to play around with this yet, but I'm super excited about it. I'll give it a shot tonight. Apologies for stalling the issue. Having stale issues in my project queues hits at my OCD, so I can definitely understand your wanting to close it out. I'll give things a shot, and close this out tonight.

**Comment by stfwi** [comment]
No worries, was just to see if this issue is still active.

**Comment by RobLoach** [comment]
Nice work. Tried it out and was able to wrap and class :+1: 

The wrapper idea that you posted above would be super handy. Using the stack is a good alternative in the mean time :wink:
